Marvin/e2e extract views 2
dfinity/internet-identity pull request #379
Opened 2021-09-07 07:02 UTC by mminder

## Description & Motivation
Separate views from test file to have a better overview over tests without scrolling a bunch first.

## How Has This Been Tested?
Tests have been executed locally and should now also run on CI.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-09-07 08:54 UTC, nmattia reviewed
I'll admit that for a newbie like me, passing the driver around explicitly made things really clear; I wonder if the (class) indirection hurts clarity. Happy to go with it if you think it's a net improvement though! I'll let @kritzcreek be the judge

2021-09-07 12:48 UTC, kritzcreek requested changes
Looks good in general 👍 I'd like to move the initialization of the view objects closer to their usage, like we're already doing it in the smaller tests.

2021-09-07 12:48 UTC, kritzcreek commented on src/frontend/src/test-e2e/flows.ts
> +    const recoveryMethodSelector = new RecoveryMethodSelector(driver);
I'd prefer initializing these right before usage instead

2021-09-07 13:18 UTC, mminder commented on src/frontend/src/test-e2e/flows.ts
> +    const recoveryMethodSelector = new RecoveryMethodSelector(driver);
done

2021-09-08 15:57 UTC, kritzcreek approved these changes

2021-09-09 07:50 UTC, merged